title: "Jad Moawad"
author: "Jad Moawad"
#description: "© 2023-24 Jad Moawad." # Made with Jekyll using the {title: contrast, url: "https://github.com/niklasbuschmann/contrast"} theme.
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: false           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: true             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  - {file: "research.md"}
  - {file: "Teaching.md"}
  #- {file: "README.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:jad.moawad@spi.ox.ac.uk"}
  - {title: Github, icon: github, url: "https://github.com/jad-moawad"}


comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
